<?php

function ajax_time_menu() {
    $items = array();
    $items['time'] = array(
        'title' => 'Ajax Test',
        'type' => MENU_NORMAL_ITEM,
        'page callback' => 'ajax_time_page',
        'access arguments' => array('access content'),
    );
    $items['time/%'] = array(
        'title' => 'Ajax Test Callback',
        'type' => MENU_CALLBACK,
        'page callback' => 'ajax_time_callback',
        'page arguments' => array(1),
        'access arguments' => array('access content'),
    );
    return $items;
}

function ajax_time_page() {
    return array(
        '#type' => 'link',
        '#title' => t('Ajax Link'),
        '#href' => 'time/nojs',
        '#prefix' => '<div id=\'ajax-link\'>',
        '#suffix' => '</div><div id=\'ajax-display\'></div>',
        '#ajax' => array(
            'effect' => 'fade',
        ),
    );
}

function ajax_time_callback($ajax) {
    $time = date('Y-m-d H:m:s');

    if ($ajax == 'ajax') {
        $commands = array();
        $commands[] = ajax_command_replace('#ajax-display', '<div id = \'ajax-display\'><p>The current time is: <br>' . $time . '<br>So put that in your pipe and smoke it</p></div>');
        $commands[] = ajax_command_changed('#ajax-display');
        $commands[] = ajax_command_invoke(NULL, 'ajax_link');
        ajax_deliver(array('#type' => 'ajax', '#commands' => $commands));
    } else {
        return array(
            '#markup' => $time,
        );
    }
}
